

import { Raleway } from 'next/font/google'
import { Sidebar } from '../components/Sidebar'
import HeroPrograms from '../components/HeroPrograms'

const inter = Raleway({ subsets: ['latin'] })

export const metadata = {
  title: 'United States Program',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <div lang="en" className='bg-white text-black'>
      <div className={inter.className}>
        <HeroPrograms text="Internship in" heading="United States" bg="usa-img" />
        <div className='layout md:p-20 h-full'>
          <Sidebar place='united-states'/>
          {children}
        </div>
      </div>
    </div>
  )
}
