

import { Raleway } from 'next/font/google'
import HeroPrograms from '../components/HeroPrograms'
import { Sidebar } from '../components/Sidebar'

const inter = Raleway({ subsets: ['latin'] })

export const metadata = {
  title: 'United Kingdom Program',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div lang="en" className='bg-white text-black'>
      <div className={inter.className}>
        <HeroPrograms text="Internship in" heading="United Kingdom" bg="uk-img" />
        <div className='layout md:p-20 h-full'>
          <Sidebar place='united-kingdom' />
          {children}
        </div>
      </div>
    </div>
  )
}
