

import { Raleway } from 'next/font/google'
import HeroPrograms from '../components/HeroPrograms'
import { Sidebar } from '../components/Sidebar'

const inter = Raleway({ subsets: ['latin'] })

export const metadata = {
  title: 'Denmark Program',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div lang="en" className='bg-white text-black'>
      <HeroPrograms text="Internship in" heading="Denmark" bg="denmark-img" />
      <div className='layout md:py-20 md:px-20 h-full'>
        <Sidebar place='denmark' />
        {children}
      </div>
    </div>
  )
}
