
import { Raleway } from 'next/font/google'
import { Metadata } from 'next'
import ClientComponent from './clientLayou'

const inter = Raleway({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Dashboard',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    
    return (
        <div lang="en" className='bg-white text-black'>
            <div className={inter.className}>
                <ClientComponent>
                    {children}
                </ClientComponent>
            </div>
        </div>
    )
}

